


export const fakeUsers = [
	{
	  full_name: 'John Doe',
	  email: 'john.doe@example.com',
	  phone: '1234567890',
	  password: 'password123',
	  role: 'user',
	  status: 'active',
	  avatar: 'john.jpg',
	},
	{
	  full_name: 'Jane Smith',
	  email: 'jane.smith@example.com',
	  phone: '0987654321',
	  password: 'password123',
	  role: 'admin',
	  status: 'active',
	  avatar: 'jane.jpg',
	},
	{
	  full_name: 'Alice Johnson',
	  email: 'alice.johnson@example.com',
	  phone: '1122334455',
	  password: 'password123',
	  role: 'venue',
	  status: 'inActive',
	  avatar: 'alice.jpg',
	},
	{
	  full_name: 'Bob Brown',
	  email: 'bob.brown@example.com',
	  phone: '5566778899',
	  password: 'password123',
	  role: 'user',
	  status: 'active',
	  avatar: 'bob.jpg',
	},
	{
	  full_name: 'Charlie Davis',
	  email: 'charlie.davis@example.com',
	  phone: '9988776655',
	  password: 'password123',
	  role: 'admin',
	  status: 'active',
	  avatar: 'charlie.jpg',
	},
	{
	  full_name: 'Diana Evans',
	  email: 'diana.evans@example.com',
	  phone: '4433221100',
	  password: 'password123',
	  role: 'venue',
	  status: 'inActive',
	  avatar: 'diana.jpg',
	},
	{
	  full_name: 'Eve Foster',
	  email: 'eve.foster@example.com',
	  phone: '6677889900',
	  password: 'password123',
	  role: 'user',
	  status: 'active',
	  avatar: 'eve.jpg',
	},
	{
	  full_name: 'Frank Green',
	  email: 'frank.green@example.com',
	  phone: '5544332211',
	  password: 'password123',
	  role: 'admin',
	  status: 'active',
	  avatar: 'frank.jpg',
	},
	{
	  full_name: 'Grace Hall',
	  email: 'grace.hall@example.com',
	  phone: '1122334455',
	  password: 'password123',
	  role: 'venue',
	  status: 'inActive',
	  avatar: 'grace.jpg',
	},
	{
	  full_name: 'Henry Irving',
	  email: 'henry.irving@example.com',
	  phone: '9988776655',
	  password: 'password123',
	  role: 'user',
	  status: 'active',
	  avatar: 'henry.jpg',
	},
  ];


  export const fakeVenues = [
	{ propertyId: 1, name: 'Grand Ballroom' },
	{ propertyId: 2, name: 'Beachside Pavilion' },
	{ propertyId: 3, name: 'Mountain Hall' },
	{ propertyId: 4, name: 'City Conference Room' },
	{ propertyId: 5, name: 'Farmhouse Barn' },
	{ propertyId: 6, name: 'Lakeview Terrace' },
	{ propertyId: 7, name: 'Ski Lodge' },
	{ propertyId: 8, name: 'Urban Rooftop' },
	{ propertyId: 9, name: 'Desert Oasis' },
	{ propertyId: 10, name: 'Forest Retreat' },
  ];


  export const fakeCities = [
	{ name: 'New York' },
	{ name: 'Los Angeles' },
	{ name: 'London' },
	{ name: 'Paris' },
	{ name: 'Tokyo' },
	{ name: 'Dubai' },
	{ name: 'Sydney' },
	{ name: 'Berlin' },
	{ name: 'Rome' },
	{ name: 'Cairo' },
  ];


  export const fakeProperties = [
	{
	  name: { en: 'Luxury Villa', ar: 'فيلا فاخرة' },
	  description: { en: 'A beautiful luxury villa with a pool.', ar: 'فيلا فاخرة مع مسبح.' },
	  file: 'villa.jpg',
	  vendorId: 1,
	  cityId: 1,
	},
	{
	  name: { en: 'Beach House', ar: 'منزل على الشاطئ' },
	  description: { en: 'A cozy beach house with ocean views.', ar: 'منزل على الشاطئ بإطلالة على المحيط.' },
	  file: 'beach-house.jpg',
	  vendorId: 2,
	  cityId: 2,
	},
	{
	  name: { en: 'Mountain Cabin', ar: 'كوخ جبلي' },
	  description: { en: 'A rustic cabin in the mountains.', ar: 'كوخ جبلي ريفي.' },
	  file: 'cabin.jpg',
	  vendorId: 3,
	  cityId: 3,
	},
	{
	  name: { en: 'City Apartment', ar: 'شقة في المدينة' },
	  description: { en: 'A modern apartment in the city center.', ar: 'شقة عصرية في وسط المدينة.' },
	  file: 'apartment.jpg',
	  vendorId: 4,
	  cityId: 4,
	},
	{
	  name: { en: 'Countryside Farmhouse', ar: 'منزل ريفي' },
	  description: { en: 'A charming farmhouse in the countryside.', ar: 'منزل ريفي ساحر في الريف.' },
	  file: 'farmhouse.jpg',
	  vendorId: 5,
	  cityId: 5,
	},
	{
	  name: { en: 'Lake House', ar: 'منزل على البحيرة' },
	  description: { en: 'A serene house by the lake.', ar: 'منزل هادئ على البحيرة.' },
	  file: 'lake-house.jpg',
	  vendorId: 6,
	  cityId: 6,
	},
	{
	  name: { en: 'Ski Chalet', ar: 'شاليه تزلج' },
	  description: { en: 'A cozy chalet near the ski slopes.', ar: 'شاليه دافئ بالقرب من منحدرات التزلج.' },
	  file: 'chalet.jpg',
	  vendorId: 7,
	  cityId: 7,
	},
	{
	  name: { en: 'Urban Loft', ar: 'لوفت حضري' },
	  description: { en: 'A stylish loft in the urban area.', ar: 'لوفت أنيق في المنطقة الحضرية.' },
	  file: 'loft.jpg',
	  vendorId: 8,
	  cityId: 8,
	},
	{
	  name: { en: 'Desert Retreat', ar: 'منتجع صحراوي' },
	  description: { en: 'A peaceful retreat in the desert.', ar: 'منتجع صحراوي هادئ.' },
	  file: 'desert-retreat.jpg',
	  vendorId: 9,
	  cityId: 9,
	},
	{
	  name: { en: 'Treehouse', ar: 'منزل على الشجرة' },
	  description: { en: 'A unique treehouse in the forest.', ar: 'منزل فريد على الشجرة في الغابة.' },
	  file: 'treehouse.jpg',
	  vendorId: 10,
	  cityId: 10,
	},
  ];